language: cpp
sudo: false

addons: &addons
  apt:
    packages: &packages
      - g++-4.9

    sources: &sources
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.4
      - llvm-toolchain-precise-3.5
      - llvm-toolchain-precise-3.6
      - llvm-toolchain-precise-3.7
      - llvm-toolchain-precise


matrix:
  include:

    - env: COMPILER='g++-5'  CXXFLAGS='-std=c++11 -v'
      addons:
        apt:
          packages: g++-5
          sources: *sources

    - env: COMPILER='clang++-3.6' CXXFLAGS='-std=c++11 -v'
      addons:
        apt:
          packages: clang-3.6
          sources: *sources
    
    - env: COMPILER='clang++-3.6' CXXFLAGS='-std=c++14 -v'
      addons:
        apt:
          packages: clang-3.6
          sources: *sources

    - env: COMPILER='clang++-3.7' CXXFLAGS='-std=c++11 -v'
      addons:
        apt:
          packages: clang-3.7
          sources: *sources

    - env: COMPILER='clang++-3.7' CXXFLAGS='-std=c++14 -v'
      addons:
        apt:
          packages: clang-3.7
          sources: *sources

before_script:
  - export CXX=$COMPILER

script: make && make test
