os:
  - Visual Studio 2017
  - Visual Studio 2015

install:
  - git submodule update --init --recursive

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

before_build:
  - cmake -H. -BBuild -A%PLATFORM%

build:
  project: Build\eytzinger.sln

test_script:
  - cd Build
  - ctest -C %CONFIGURATION%
